### ISSUE TITLE
Statsmodels Wrapper

### ISSUE THREAD

**Issue by marianturowski** [KIT-IAI/pyWATTS#29] opened 2020-12-08 14:26 UTC
**What is your feature request related to?**
* Module request

**Please describe the module/problem**

Methods from [Statsmodels](https://www.statsmodels.org/devel/index.html) cannot be directly used in a pipeline

**Describe the solution you'd like**

A wrapper that allows to directly use methods from Statsmodels (analogously to the sklearn wrapper)

**Comment by SMEISEN** [comment] 2020-12-18 22:39
duplicate of #14?

**Comment by kalebphipps** [comment] 2020-12-21 11:49
Yep, closed since this is a duplicate of issue #14

**Closed by kalebphipps** 2020-12-21 11:49 UTC
Labels: duplicate, enhancement, high, module
